import TorusEven

#print axioms TorusEven.Surgery.singleCycle_of_induced_orbits
#print axioms TorusEven.Entry.Star.mem_support_iff
#print axioms TorusEven.Entry.Star.natCast_eq_iff_four
#print axioms TorusEven.Entry.Star.hitTest_iff
#print axioms TorusEven.Entry.Star.translation_ret_nat
#print axioms TorusEven.Entry.Star.InnerReturn.theta_injective
#print axioms TorusEven.Entry.Star.InnerReturn.thetaPerm
#print axioms TorusEven.Entry.Star.Divisible.nu_x_low
#print axioms TorusEven.Entry.Star.Divisible.nu_x_middle
#print axioms TorusEven.Entry.Star.Divisible.nu_x_high
#print axioms TorusEven.Entry.Star.Divisible.nu_y_axis
#print axioms TorusEven.Entry.Star.Divisible.nu_y_fixed
#print axioms TorusEven.Entry.Star.Divisible.nu_y_four
#print axioms TorusEven.Entry.Star.Divisible.nu_y_end
#print axioms TorusEven.Entry.Star.Divisible.nu_cornerPlus
#print axioms TorusEven.Entry.Star.Divisible.nu_cornerMinus
#print axioms TorusEven.Entry.Star.Divisible.phi_word
#print axioms TorusEven.Entry.Star.Divisible.phi_x_high
#print axioms TorusEven.Entry.Star.Divisible.phi_y_fixed
#print axioms TorusEven.Entry.Star.Divisible.return_x_low
#print axioms TorusEven.Entry.Star.Divisible.return_x_middle
#print axioms TorusEven.Entry.Star.Divisible.return_x_four
#print axioms TorusEven.Entry.Star.Divisible.return_x_four_succ
#print axioms TorusEven.Entry.Star.Divisible.return_x_high
#print axioms TorusEven.Entry.Star.Divisible.return_x_penultimate
#print axioms TorusEven.Entry.Star.Divisible.return_x_last
#print axioms TorusEven.Entry.Star.Divisible.psi_val
#print axioms TorusEven.Entry.Star.Divisible.psi_inner_return
#print axioms TorusEven.Entry.Star.Divisible.psi_meets_inner
#print axioms TorusEven.Entry.Star.Divisible.psi_hamilton
#print axioms TorusEven.Entry.Star.Divisible.return_x_table
#print axioms TorusEven.Entry.Star.Divisible.psiIndex_succ
#print axioms TorusEven.Entry.Star.Divisible.phi_ret_x
#print axioms TorusEven.Entry.Star.Divisible.y_meets_x
#print axioms TorusEven.Entry.Star.Divisible.phi_meets_x
#print axioms TorusEven.Entry.Star.Divisible.phi_hamilton
#print axioms TorusEven.Entry.Star.Divisible.sum_return_times
#print axioms TorusEven.Entry.Star.return_hamilton_three_dvd
#print axioms TorusEven.Entry.Star.hamilton_three_dvd
#print axioms TorusEven.Entry.Star.replacement_hamilton_three_dvd
#print axioms TorusEven.Entry.Star.hamilton_four
#print axioms TorusEven.Entry.Star.hamilton_six
#print axioms TorusEven.Entry.anchorVoltage_gapSupport
#print axioms TorusEven.even_degree_collar
#print axioms TorusEven.even_modulus_tori_all_dimensions_of_collar
