import TorusEven

#print axioms TorusEven.Surgery.exists_openGap
#print axioms TorusEven.Surgery.supported_perm_mem_iff
#print axioms TorusEven.Collar.singleVoltage_of_pair
#print axioms TorusEven.Collar.unitCarry_of_singleCycle
#print axioms TorusEven.Collar.SingleVoltage.unit
#print axioms TorusEven.Collar.gapSupport_of_single_source
#print axioms TorusEven.Collar.Recolouring.ofReplacement
#print axioms TorusEven.Collar.Recolouring.ofReplacement_step
#print axioms TorusEven.Collar.Recolouring.split
#print axioms TorusEven.Collar.Recolouring.split_circuitCount
#print axioms TorusEven.Collar.Recolouring.split_hamilton
#print axioms TorusEven.Collar.BlockSelection.enters_collar
#print axioms TorusEven.Collar.hamilton_decomposition_of_entry
#print axioms TorusEven.Entry.anchor_agreement
#print axioms TorusEven.Entry.heightLift_return
#print axioms TorusEven.Entry.heightLift_retTime
#print axioms TorusEven.Entry.heightLift_retPerm
#print axioms TorusEven.Entry.heightLift_section_orbit
#print axioms TorusEven.Entry.heightLift_circuitCount
#print axioms TorusEven.Entry.negTwo_orbit_iff
#print axioms TorusEven.Entry.negTwo_circuitCount
#print axioms TorusEven.Entry.NearCore.factorization
#print axioms TorusEven.Entry.NearCore.hamilton
#print axioms TorusEven.Entry.NearCore.yVoltage_two_single
#print axioms TorusEven.Entry.NearCore.unit
#print axioms TorusEven.Entry.NearCore.consistent
#print axioms TorusEven.Entry.NearCore.circuitCount
#print axioms TorusEven.Entry.NearCore.circuitLabel_card
#print axioms TorusEven.Entry.NearCore.baseDefect_step
#print axioms TorusEven.Entry.NearCore.orbit_defect_iff
#print axioms TorusEven.Entry.NearCore.orbit_card_two
#print axioms TorusEven.Entry.anchor_outside
#print axioms TorusEven.Entry.anchor_direction
#print axioms TorusEven.Entry.xChart_consistent
#print axioms TorusEven.Entry.anchorEquiv
#print axioms TorusEven.Entry.anchorLabel_mem
#print axioms TorusEven.Entry.anchorVoltage_single
#print axioms TorusEven.Entry.anchorVoltage_unit
#print axioms TorusEven.Entry.anchorVoltage_gapSupport
#print axioms TorusEven.even_degree_collar
#print axioms TorusEven.even_modulus_tori_all_dimensions_of_collar
