import TorusEven

#print axioms TorusEven.Entry.Star.turn_ray
#print axioms TorusEven.Entry.Star.turn_generator
#print axioms TorusEven.Entry.Star.row_rotate
#print axioms TorusEven.Entry.Star.surgeryMap_rotate
#print axioms TorusEven.Entry.Star.wordStep_singleCycle
#print axioms TorusEven.Entry.Star.word_injective
#print axioms TorusEven.Entry.Star.surgery_zero_outside
#print axioms TorusEven.Entry.Star.surgery_word
#print axioms TorusEven.Entry.Star.zeroPerm_apply
#print axioms TorusEven.Entry.Star.surgeryPerm_apply
#print axioms TorusEven.Entry.Star.layer_apply
#print axioms TorusEven.Entry.Star.heightStep
#print axioms TorusEven.Entry.Star.step_eq
#print axioms TorusEven.Entry.Star.factorization
#print axioms TorusEven.Entry.Star.replacement
#print axioms TorusEven.Entry.Star.replacement_step
#print axioms TorusEven.Entry.Star.sum_height_translate
#print axioms TorusEven.Entry.Star.oneSpecial_return
#print axioms TorusEven.Entry.Star.singleCycle_of_section
#print axioms TorusEven.Entry.Star.carry_sum
#print axioms TorusEven.Entry.Star.voltage_rotate
#print axioms TorusEven.Entry.Star.height_return
#print axioms TorusEven.Entry.Star.returnMap_rotate
#print axioms TorusEven.Entry.Star.return_singleCycle
#print axioms TorusEven.Entry.Star.hamilton_of_return
#print axioms TorusEven.Entry.Star.replacement_hamilton_of_return
#print axioms TorusEven.Entry.Star.return_hamilton_four
#print axioms TorusEven.Entry.Star.return_hamilton_six
#print axioms TorusEven.Entry.Star.hamilton_four
#print axioms TorusEven.Entry.Star.hamilton_six
#print axioms TorusEven.Entry.Star.support_card
#print axioms TorusEven.Entry.Star.zeroPerm_orbit_word
#print axioms TorusEven.Entry.Star.zeroPerm_orbit_card
#print axioms TorusEven.Entry.Star.voltage_meets_support
#print axioms TorusEven.Entry.Star.boundaryExtension_eq
#print axioms TorusEven.Entry.Star.markedReturn_word
#print axioms TorusEven.Entry.Star.return_circuitCount
#print axioms TorusEven.Entry.Star.hamilton_of_markedReturn
#print axioms TorusEven.Entry.Star.InnerReturn.order
#print axioms TorusEven.Entry.Star.InnerReturn.step_order
#print axioms TorusEven.Entry.Star.InnerReturn.hamilton
#print axioms TorusEven.Entry.anchorVoltage_gapSupport
#print axioms TorusEven.even_degree_collar
#print axioms TorusEven.even_modulus_tori_all_dimensions_of_collar
