import TorusEven

#print axioms TorusEven.Collar.Multigraph.degree
#print axioms TorusEven.Collar.Multigraph.sum_degree
#print axioms TorusEven.Collar.Multigraph.exists_half_orientation
#print axioms TorusEven.Collar.Multigraph.Reorients
#print axioms TorusEven.Collar.Multigraph.divergence
#print axioms TorusEven.Collar.Multigraph.exists_even_orientation
#print axioms TorusEven.Collar.Multigraph.exists_mixed_orientation
#print axioms TorusEven.Collar.Multigraph.exists_odd_orientation
#print axioms TorusEven.Collar.Incidence.Adjacent
#print axioms TorusEven.Collar.Incidence.Component
#print axioms TorusEven.Collar.Incidence.componentOf
#print axioms TorusEven.Collar.Incidence.componentOf_eq
#print axioms TorusEven.Collar.Incidence.EvenComponents
#print axioms TorusEven.Collar.Incidence.EvenOnComponents
#print axioms TorusEven.Collar.Incidence.evenOnComponents_univ
#print axioms TorusEven.Collar.Incidence.EvenOnComponents.sum
#print axioms TorusEven.Collar.Incidence.same_component
#print axioms TorusEven.Collar.Incidence.evenComponents_of_universal_block
#print axioms TorusEven.Collar.Incidence.blockComponent
#print axioms TorusEven.Collar.Incidence.component_eq_block
#print axioms TorusEven.Collar.Incidence.Coherent
#print axioms TorusEven.Collar.Incidence.coherent_blockComponent
#print axioms TorusEven.Collar.Incidence.copied_component_iff
#print axioms TorusEven.Collar.Incidence.evenComponents_copied
#print axioms TorusEven.Collar.LocalPairs
#print axioms TorusEven.Collar.LocalPairs.reverse
#print axioms TorusEven.Collar.LocalPairs.reverse_endpoint
#print axioms TorusEven.Collar.LocalPairs.support
#print axioms TorusEven.Collar.LocalPairs.mem_support
#print axioms TorusEven.Collar.LocalPairs.support_subset
#print axioms TorusEven.Collar.LocalPairs.card_support
#print axioms TorusEven.Collar.LocalPairs.count_le
#print axioms TorusEven.Collar.LocalPairs.divergence
#print axioms TorusEven.Collar.Incidence.exists_directed_pairs_on
#print axioms TorusEven.Collar.Incidence.exists_directed_pairs
#print axioms TorusEven.Collar.Incidence.evenComponents_of_boundary
#print axioms TorusEven.Collar.Incidence.exists_parity_join_on
#print axioms TorusEven.Collar.Incidence.exists_parity_join
#print axioms TorusEven.Collar.LocalPairs.exists_event_bits
#print axioms TorusEven.Collar.LocalPairs.exists_fillers
#print axioms TorusEven.Collar.LocalPairs.exists_fillers_of_quota
#print axioms TorusEven.Collar.LocalPairs.row_pinned
#print axioms TorusEven.Collar.Incidence.MatchedData.pattern_sum
#print axioms TorusEven.Collar.Incidence.MatchedData.active_card
#print axioms TorusEven.Collar.Incidence.MatchedData.sum_mate_indicator
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.auxiliary_sum
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.auxiliary_carry
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.row_coherent_none
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.selected_coherent
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.complement_coherent
#print axioms TorusEven.Collar.Incidence.MatchedData
#print axioms TorusEven.Collar.Incidence.MatchedData.query
#print axioms TorusEven.Collar.Incidence.MatchedData.query_some
#print axioms TorusEven.Collar.Incidence.MatchedData.query_anchor
#print axioms TorusEven.Collar.Incidence.MatchedData.query_none
#print axioms TorusEven.Collar.Incidence.MatchedData.active_of_query
#print axioms TorusEven.Collar.Incidence.MatchedData.eligible_of_query
#print axioms TorusEven.Collar.Incidence.MatchedData.mates
#print axioms TorusEven.Collar.Incidence.MatchedData.mem_mates
#print axioms TorusEven.Collar.Incidence.MatchedData.nonmates
#print axioms TorusEven.Collar.Incidence.MatchedData.mem_nonmates
#print axioms TorusEven.Collar.Incidence.MatchedData.residual
#print axioms TorusEven.Collar.Incidence.MatchedData.quota
#print axioms TorusEven.Collar.Incidence.MatchedData.residual_subset
#print axioms TorusEven.Collar.Incidence.MatchedData.mate_not_residual
#print axioms TorusEven.Collar.Incidence.MatchedData.residual_card
#print axioms TorusEven.Collar.Incidence.MatchedData.quota_bounds
#print axioms TorusEven.Collar.Incidence.MatchedData.fullSupport
#print axioms TorusEven.Collar.Incidence.MatchedData.card_fullSupport
#print axioms TorusEven.Collar.Incidence.MatchedData.pattern
#print axioms TorusEven.Collar.Incidence.MatchedData.mem_pattern_left
#print axioms TorusEven.Collar.Incidence.MatchedData.sum_query
#print axioms TorusEven.Collar.Incidence.MatchedData.pattern_subset
#print axioms TorusEven.Collar.Incidence.MatchedData.pattern_card
#print axioms TorusEven.Collar.Incidence.MatchedData.fullSupport_some
#print axioms TorusEven.Collar.Incidence.MatchedData.complement_pattern
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows
#print axioms TorusEven.Collar.Incidence.MatchedData.rowsOfPairs
#print axioms TorusEven.Collar.Incidence.MatchedData.rowsOfPairs_pairs
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.event
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.row
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.row_subset
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.row_card
#print axioms TorusEven.Collar.Incidence.MatchedData.ResidualRows.row_baseline
#print axioms TorusEven.Collar.Incidence.MatchedData.exists_selection
#print axioms TorusEven.Collar.switchedRow
#print axioms TorusEven.Collar.switchedRow_subset
#print axioms TorusEven.Collar.card_switchedRow
#print axioms TorusEven.Collar.complement_switchedRow
#print axioms TorusEven.Collar.coherent_switchedRow
#print axioms TorusEven.Collar.coherent_insert
#print axioms TorusEven.Collar.fourRanks
#print axioms TorusEven.Collar.fourRanks_zero
#print axioms TorusEven.Collar.sum_switchedRows
#print axioms TorusEven.Collar.Incidence.exists_pinnedSelection
#print axioms TorusEven.even_degree_collar
#print axioms TorusEven.even_modulus_tori_all_dimensions_of_collar
