-- STATUS: main-path (integer matrix certificates: complements and kernels over ZMod m)
import Mathlib

/-!
# Integer certificates over `ZMod m`

Interface 2 of `evidence/even_d5/INTERFACES.md`.  A column span `H` (generated by the columns
of `Hm`) and a kernel `W = ker L` are complementary as soon as the `r × r` matrix `L * Hm`
has an integer inverse; a kernel `ker f` equals a column span as soon as `[Hm | u]` has an
integer inverse whose last row is `f`.  All identities are checked over `ℤ` and transported
to `ZMod m` by the cast ring homomorphism, so nothing depends on `m`.
-/

namespace TorusEven
namespace Cert

open Matrix

variable {m : ℕ} {r : ℕ}

abbrev V (m : ℕ) := Fin 4 → ZMod m

/-- Cast an integer matrix to `ZMod m`. -/
def castM {p q : ℕ} (A : Matrix (Fin p) (Fin q) ℤ) : Matrix (Fin p) (Fin q) (ZMod m) :=
  A.map (Int.castRingHom (ZMod m))

/-- Cast an integer vector to `ZMod m`. -/
def castV {p : ℕ} (v : Fin p → ℤ) : Fin p → ZMod m := fun i => (v i : ZMod m)

@[simp] theorem castM_apply {p q : ℕ} (A : Matrix (Fin p) (Fin q) ℤ) (i j) :
    castM (m := m) A i j = (A i j : ZMod m) := rfl

theorem castM_mulVec_castV {p q : ℕ} (A : Matrix (Fin p) (Fin q) ℤ) (v : Fin q → ℤ) :
    castM (m := m) A *ᵥ castV v = castV (A *ᵥ v) := by
  funext i
  simp [Matrix.mulVec, dotProduct, castM, castV]

theorem castV_lift [NeZero m] {p : ℕ} (v : Fin p → ZMod m) :
    castV (m := m) (fun i => ((v i).val : ℤ)) = v := by
  funext i
  simp [castV, ZMod.natCast_zmod_val]

/-- Transport a vector identity `A *ᵥ (B *ᵥ (C *ᵥ v)) = v` from `ℤ` to `ZMod m`. -/
theorem triple_of_int [NeZero m] {p q s : ℕ} (A : Matrix (Fin p) (Fin q) ℤ)
    (B : Matrix (Fin q) (Fin s) ℤ) (C : Matrix (Fin s) (Fin p) ℤ)
    (h : ∀ v : Fin p → ℤ, A *ᵥ (B *ᵥ (C *ᵥ v)) = v) (v : Fin p → ZMod m) :
    castM (m := m) A *ᵥ (castM B *ᵥ (castM C *ᵥ v)) = v := by
  rw [← castV_lift v, castM_mulVec_castV, castM_mulVec_castV, castM_mulVec_castV, h]

theorem double_of_int [NeZero m] {p q : ℕ} (A : Matrix (Fin p) (Fin q) ℤ)
    (B : Matrix (Fin q) (Fin p) ℤ)
    (h : ∀ v : Fin p → ℤ, A *ᵥ (B *ᵥ v) = v) (v : Fin p → ZMod m) :
    castM (m := m) A *ᵥ (castM B *ᵥ v) = v := by
  rw [← castV_lift v, castM_mulVec_castV, castM_mulVec_castV, h]

/-- The column span of `Hm` as an additive subgroup. -/
def colSpan (Hm : Matrix (Fin 4) (Fin r) (ZMod m)) : AddSubgroup (V m) :=
  (Matrix.mulVecLin Hm).range.toAddSubgroup

theorem mem_colSpan {Hm : Matrix (Fin 4) (Fin r) (ZMod m)} {x : V m} :
    x ∈ colSpan Hm ↔ ∃ a, Hm *ᵥ a = x := by
  simp [colSpan, LinearMap.mem_range]

/-- The kernel of `L` as an additive subgroup. -/
def kerOf (L : Matrix (Fin r) (Fin 4) (ZMod m)) : AddSubgroup (V m) :=
  (Matrix.mulVecLin L).ker.toAddSubgroup

theorem mem_kerOf {L : Matrix (Fin r) (Fin 4) (ZMod m)} {x : V m} :
    x ∈ kerOf L ↔ L *ᵥ x = 0 := by
  simp [kerOf, LinearMap.mem_ker]

instance decidableMemKerOf (L : Matrix (Fin r) (Fin 4) (ZMod m)) :
    DecidablePred (· ∈ kerOf L) :=
  fun _ => decidable_of_iff _ mem_kerOf.symm

/-! ### Complements -/

/-- `IsCompl (colSpan Hm) (kerOf L)` from an integer inverse of `L * Hm`. -/
theorem isCompl_of_inverse [NeZero m] (Hz : Matrix (Fin 4) (Fin r) ℤ)
    (Lz : Matrix (Fin r) (Fin 4) ℤ) (Minv : Matrix (Fin r) (Fin r) ℤ)
    (h1 : ∀ v : Fin r → ℤ, Lz *ᵥ (Hz *ᵥ (Minv *ᵥ v)) = v)
    (h2 : ∀ v : Fin r → ℤ, Minv *ᵥ (Lz *ᵥ (Hz *ᵥ v)) = v) :
    IsCompl (colSpan (castM (m := m) Hz)) (kerOf (castM (m := m) Lz)) := by
  have h1' := triple_of_int (m := m) Lz Hz Minv h1
  have h2' := triple_of_int (m := m) Minv Lz Hz h2
  constructor
  · rw [AddSubgroup.disjoint_def]
    intro x hx hk
    obtain ⟨a, rfl⟩ := mem_colSpan.1 hx
    have hk' : castM (m := m) Lz *ᵥ (castM Hz *ᵥ a) = 0 := mem_kerOf.1 hk
    have ha : a = 0 := by
      rw [← h2' a, hk', Matrix.mulVec_zero]
    rw [ha, Matrix.mulVec_zero]
  · rw [codisjoint_iff, eq_top_iff]
    intro y _
    set a := castM (m := m) Minv *ᵥ (castM Lz *ᵥ y) with ha
    refine AddSubgroup.mem_sup.2
      ⟨castM Hz *ᵥ a, mem_colSpan.2 ⟨a, rfl⟩, y - castM Hz *ᵥ a, ?_, by abel⟩
    rw [mem_kerOf, Matrix.mulVec_sub, sub_eq_zero, ha, h1']

/-! ### Growing a column span by one generator -/

/-- Prepend the column `e` to `Hz`. -/
def prepend (e : Fin 4 → ℤ) (Hz : Matrix (Fin 4) (Fin r) ℤ) : Matrix (Fin 4) (Fin (r + 1)) ℤ :=
  Matrix.of fun i j => Fin.cases (e i) (fun j' => Hz i j') j

theorem castM_prepend_mulVec (e : Fin 4 → ℤ) (Hz : Matrix (Fin 4) (Fin r) ℤ)
    (b : Fin (r + 1) → ZMod m) :
    castM (m := m) (prepend e Hz) *ᵥ b = b 0 • castV e + castM Hz *ᵥ Fin.tail b := by
  funext i
  simp [Matrix.mulVec, dotProduct, prepend, castM, castV, Fin.sum_univ_succ, Fin.tail, mul_comm]

theorem zmod_smul_eq_zsmul [NeZero m] (a : ZMod m) (v : V m) : a • v = (a.val : ℤ) • v := by
  rw [natCast_zsmul]
  funext i
  simp [nsmul_eq_mul, ZMod.natCast_zmod_val]

theorem zsmul_eq_zmod_smul (k : ℤ) (v : V m) : k • v = (k : ZMod m) • v :=
  (Int.cast_smul_eq_zsmul (ZMod m) k v).symm

theorem colSpan_prepend [NeZero m] (e : Fin 4 → ℤ) (Hz : Matrix (Fin 4) (Fin r) ℤ) :
    colSpan (castM (m := m) (prepend e Hz)) =
      colSpan (castM Hz) ⊔ AddSubgroup.zmultiples (castV e) := by
  ext x
  rw [mem_colSpan, AddSubgroup.mem_sup]
  constructor
  · rintro ⟨b, rfl⟩
    rw [castM_prepend_mulVec]
    refine ⟨castM Hz *ᵥ Fin.tail b, mem_colSpan.2 ⟨_, rfl⟩, b 0 • castV e, ?_, by abel⟩
    rw [zmod_smul_eq_zsmul]
    exact AddSubgroup.mem_zmultiples_iff.2 ⟨_, rfl⟩
  · rintro ⟨y, hy, z, hz, rfl⟩
    obtain ⟨a, rfl⟩ := mem_colSpan.1 hy
    obtain ⟨k, rfl⟩ := AddSubgroup.mem_zmultiples_iff.1 hz
    refine ⟨Fin.cons (k : ZMod m) a, ?_⟩
    rw [castM_prepend_mulVec, Fin.cons_zero, Fin.tail_cons, zsmul_eq_zmod_smul]
    abel

/-! ### Full rank and kernels of characters -/

theorem colSpan_eq_top_of_inverse [NeZero m] (Hz Hinv : Matrix (Fin 4) (Fin 4) ℤ)
    (h : ∀ v : Fin 4 → ℤ, Hz *ᵥ (Hinv *ᵥ v) = v) :
    colSpan (castM (m := m) Hz) = ⊤ := by
  rw [eq_top_iff]
  intro y _
  exact mem_colSpan.2 ⟨castM Hinv *ᵥ y, double_of_int (m := m) Hz Hinv h y⟩

/-- Append the column `u` to a `4 × 3` matrix. -/
def augment (Hz : Matrix (Fin 4) (Fin 3) ℤ) (u : Fin 4 → ℤ) : Matrix (Fin 4) (Fin 4) ℤ :=
  Matrix.of fun i j => if h : j.val < 3 then Hz i ⟨j.val, h⟩ else u i

theorem castM_augment_mulVec (Hz : Matrix (Fin 4) (Fin 3) ℤ) (u : Fin 4 → ℤ)
    (b : Fin 4 → ZMod m) :
    castM (m := m) (augment Hz u) *ᵥ b =
      castM Hz *ᵥ (fun j => b j.castSucc) + b (Fin.last 3) • castV u := by
  funext i
  simp [Matrix.mulVec, dotProduct, augment, castM, castV, Fin.sum_univ_four, Fin.sum_univ_three,
    Fin.last]
  ring

/-- The row `f` as a `1 × 4` matrix. -/
def rowM (f : Fin 4 → ℤ) : Matrix (Fin 1) (Fin 4) ℤ := Matrix.of fun _ j => f j

theorem mem_kerOf_rowM {f : Fin 4 → ℤ} {x : V m} :
    x ∈ kerOf (castM (m := m) (rowM f)) ↔ ∑ j, (f j : ZMod m) * x j = 0 := by
  rw [mem_kerOf]
  constructor
  · intro h
    have := congrFun h 0
    simpa [Matrix.mulVec, dotProduct, rowM, castM] using this
  · intro h
    funext i
    simpa [Matrix.mulVec, dotProduct, rowM, castM] using h

/-- If `[Hz | u]` has an integer inverse `Qinv` whose last row is `f`, then `ker f` is the
column span of `Hz`. -/
theorem kerOf_rowM_eq_colSpan [NeZero m] (Hz : Matrix (Fin 4) (Fin 3) ℤ) (u : Fin 4 → ℤ)
    (Qinv : Matrix (Fin 4) (Fin 4) ℤ) (f : Fin 4 → ℤ)
    (h1 : ∀ v : Fin 4 → ℤ, augment Hz u *ᵥ (Qinv *ᵥ v) = v)
    (h2 : ∀ v : Fin 4 → ℤ, Qinv *ᵥ (augment Hz u *ᵥ v) = v)
    (hf : ∀ j, Qinv 3 j = f j) :
    kerOf (castM (m := m) (rowM f)) = colSpan (castM Hz) := by
  have h1' := double_of_int (m := m) (augment Hz u) Qinv h1
  have h2' := double_of_int (m := m) Qinv (augment Hz u) h2
  have hlast : ∀ x : V m,
      (castM (m := m) Qinv *ᵥ x) (Fin.last 3) = ∑ j, (f j : ZMod m) * x j := by
    intro x
    simp [Matrix.mulVec, dotProduct, castM, hf]
  ext x
  rw [mem_kerOf_rowM, mem_colSpan]
  constructor
  · intro hx
    refine ⟨fun j => (castM Qinv *ᵥ x) j.castSucc, ?_⟩
    conv_rhs => rw [← h1' x]
    rw [castM_augment_mulVec, hlast, hx, zero_smul, add_zero]
  · rintro ⟨a, rfl⟩
    have hb : castM (m := m) Qinv *ᵥ (castM Hz *ᵥ a) = Fin.snoc a 0 := by
      have : castM (m := m) Hz *ᵥ a = castM (augment Hz u) *ᵥ Fin.snoc a 0 := by
        rw [castM_augment_mulVec]
        have h3 : (Fin.snoc a (0 : ZMod m) : Fin 4 → ZMod m) (Fin.last 3) = 0 :=
          Fin.snoc_last _ _
        first
        | (simp only [Fin.snoc_castSucc, h3, zero_smul, add_zero]; done)
        | (simp only [Fin.snoc_castSucc]; rw [h3, zero_smul, add_zero]; done)
        | (simp [Fin.snoc_castSucc]; rfl)
      rw [this, h2']
    rw [← hlast, hb, Fin.snoc_last]

end Cert
end TorusEven
