import TorusEven

#print axioms TorusEven.Surgery.singleCycle_of_cyclic_order
#print axioms TorusEven.Entry.Star.translation_iterate_neg_two_nat
#print axioms TorusEven.Entry.Star.translation_ret_neg_two_nat
#print axioms TorusEven.Entry.Star.Nondivisible.MeetsX
#print axioms TorusEven.Entry.Star.Nondivisible.meets_x
#print axioms TorusEven.Entry.Star.Nondivisible.meets_of_step
#print axioms TorusEven.Entry.Star.Nondivisible.plus_meets_x
#print axioms TorusEven.Entry.Star.Nondivisible.minus_meets_x
#print axioms TorusEven.Entry.Star.Nondivisible.odd_y_meets_x
#print axioms TorusEven.Entry.Star.Nondivisible.y_meets_x
#print axioms TorusEven.Entry.Star.Nondivisible.phi_meets_x
#print axioms TorusEven.Entry.Star.Nondivisible.phi_hamilton
#print axioms TorusEven.Entry.Star.Nondivisible.sum_return_times
#print axioms TorusEven.Entry.Star.Nondivisible.chiIndex
#print axioms TorusEven.Entry.Star.Nondivisible.chi
#print axioms TorusEven.Entry.Star.Nondivisible.orderIndex
#print axioms TorusEven.Entry.Star.Nondivisible.orderIndex_lt
#print axioms TorusEven.Entry.Star.Nondivisible.order
#print axioms TorusEven.Entry.Star.Nondivisible.chi_order
#print axioms TorusEven.Entry.Star.Nondivisible.chi_hamilton_residue
#print axioms TorusEven.Entry.Star.Nondivisible.chi_hamilton
#print axioms TorusEven.Entry.Star.Nondivisible.x
#print axioms TorusEven.Entry.Star.Nondivisible.y
#print axioms TorusEven.Entry.Star.Nondivisible.phi
#print axioms TorusEven.Entry.Star.Nondivisible.word_x
#print axioms TorusEven.Entry.Star.Nondivisible.word_y
#print axioms TorusEven.Entry.Star.Nondivisible.cast_last
#print axioms TorusEven.Entry.Star.Nondivisible.word_plus
#print axioms TorusEven.Entry.Star.Nondivisible.word_minus
#print axioms TorusEven.Entry.Star.Nondivisible.surgery_x
#print axioms TorusEven.Entry.Star.Nondivisible.surgery_y
#print axioms TorusEven.Entry.Star.Nondivisible.phi_word
#print axioms TorusEven.Entry.Star.Nondivisible.phi_x_low
#print axioms TorusEven.Entry.Star.Nondivisible.phi_x_middle
#print axioms TorusEven.Entry.Star.Nondivisible.phi_x_high
#print axioms TorusEven.Entry.Star.Nondivisible.phi_x_last
#print axioms TorusEven.Entry.Star.Nondivisible.phi_y_fixed
#print axioms TorusEven.Entry.Star.Nondivisible.phi_y_axis
#print axioms TorusEven.Entry.Star.Nondivisible.phi_y_penultimate
#print axioms TorusEven.Entry.Star.Nondivisible.phi_y_last
#print axioms TorusEven.Entry.Star.Nondivisible.phi_plus
#print axioms TorusEven.Entry.Star.Nondivisible.phi_minus
#print axioms TorusEven.Entry.Star.Nondivisible.psiIndex
#print axioms TorusEven.Entry.Star.Nondivisible.psiIndex_lt
#print axioms TorusEven.Entry.Star.Nondivisible.psi
#print axioms TorusEven.Entry.Star.Nondivisible.psi_val
#print axioms TorusEven.Entry.Star.Nondivisible.lowerEmbedding
#print axioms TorusEven.Entry.Star.Nondivisible.lower_step
#print axioms TorusEven.Entry.Star.Nondivisible.psi_meets_lower
#print axioms TorusEven.Entry.Star.Nondivisible.psi_hamilton
#print axioms TorusEven.Entry.Star.Nondivisible.xReturnIndex
#print axioms TorusEven.Entry.Star.Nondivisible.returnLength
#print axioms TorusEven.Entry.Star.Nondivisible.return_x_table
#print axioms TorusEven.Entry.Star.Nondivisible.psiIndex_succ
#print axioms TorusEven.Entry.Star.Nondivisible.xEmbedding
#print axioms TorusEven.Entry.Star.Nondivisible.phi_ret_x
#print axioms TorusEven.Entry.Star.Nondivisible.point
#print axioms TorusEven.Entry.Star.Nondivisible.nu
#print axioms TorusEven.Entry.Star.Nondivisible.nu_x_low
#print axioms TorusEven.Entry.Star.Nondivisible.nu_x_middle
#print axioms TorusEven.Entry.Star.Nondivisible.nu_x_high
#print axioms TorusEven.Entry.Star.Nondivisible.nu_y_axis
#print axioms TorusEven.Entry.Star.Nondivisible.nu_y_fixed
#print axioms TorusEven.Entry.Star.Nondivisible.nu_y_one
#print axioms TorusEven.Entry.Star.Nondivisible.nu_y_last
#print axioms TorusEven.Entry.Star.Nondivisible.nu_cornerPlus
#print axioms TorusEven.Entry.Star.Nondivisible.nu_cornerMinus
#print axioms TorusEven.Entry.Star.Nondivisible.horizontal
#print axioms TorusEven.Entry.Star.Nondivisible.horizontalDecidable
#print axioms TorusEven.Entry.Star.Nondivisible.x_mem
#print axioms TorusEven.Entry.Star.Nondivisible.y_not_mem
#print axioms TorusEven.Entry.Star.Nondivisible.plus_not_mem
#print axioms TorusEven.Entry.Star.Nondivisible.return_x_low
#print axioms TorusEven.Entry.Star.Nondivisible.return_x_middle
#print axioms TorusEven.Entry.Star.Nondivisible.return_x_high
#print axioms TorusEven.Entry.Star.Nondivisible.return_x_penultimate
#print axioms TorusEven.Entry.Star.Nondivisible.return_x_last
#print axioms TorusEven.Entry.Star.return_hamilton_three_not_dvd
#print axioms TorusEven.Entry.Star.hamilton_three_not_dvd
#print axioms TorusEven.Entry.Star.replacement_hamilton_three_not_dvd
#print axioms TorusEven.Entry.Star.return_hamilton
#print axioms TorusEven.Entry.Star.hamilton
#print axioms TorusEven.Entry.Star.replacement_hamilton
#print axioms TorusEven.Entry.Star.return_hamilton_three_dvd
#print axioms TorusEven.Entry.Star.replacement_hamilton_three_dvd
#print axioms TorusEven.Entry.Star.hamilton_four
#print axioms TorusEven.Entry.Star.hamilton_six
#print axioms TorusEven.Entry.anchorVoltage_gapSupport
#print axioms TorusEven.even_degree_collar
#print axioms TorusEven.even_modulus_tori_all_dimensions_of_collar
